# 认证
auth:
  jwt:
    secret: "hello"
    appid: 13

db:
  # 原文格式 ：user:password@tcp(ip:port)/database?charset=utf8mb4&parseTime=True&loc=Local&timeout=10s
  dsn: "root:1234@tcp(192.168.1.2:3306)/gorge?charset=utf8mb4&parseTime=True&loc=Local&timeout=10s" 
  maxConn: 10